name: Missing Items
description: An item is missing from the backport.
title: "[Missing]: "
labels: ["missing item"]
assignees:
  - bangetto
body:
  - type: textarea
    id: id
    attributes:
      label: What items are missing?
      description: "Write down the list of items that are missing!"
      placeholder: "Ex: sculk_sensor, sus sand"
    validations:
      required: true
  - type: checkboxes
    id: version
    attributes:
      label: Checks
      description: "Before reporting an issue please check that everything is up-today!"
      options:
        - label: "I downloaded the latest version of the repository"
          required: true
        - label: "The server has the latest snapshot of the Via* plugins"
          required: true
    validations:
      required: true
  - type: dropdown
    id: detector
    attributes:
      label: "Which one of the detector mods are present?"
      multiple: true
      options:
        - "Chime"
        - "Optifine CIT"
    validations:
        required: true
  - type: input
    id: mc
    attributes:
      label: "Your Minecraft version"
      description: "Write down your Minecraft option"
      placeholder: "Example: 1.16.5"
    validations:
        required: true
