name: "Outdated Texture[s]"
description: A texture not been updated to use the latest one.
title: "[Outdated]: "
labels: ["outdated texture"]
assignees:
  - bangetto
body:
  - type: textarea
    id: main
    attributes:
      label: "What texture[s] are outdated?"
      description: "Write down the list textures that are outdated!"
      placeholder: "Ex: grass_side or the side texture of grass"
    validations:
      required: true
  - type: checkboxes
    id: version
    attributes:
      label: Checks
      description: "Before reporting an issue please check that everything is up-today!"
      options:
        - label: "I downloaded the latest version of the repository"
          required: true
        - label: "There are no resources pack above this"
          required: true
    validations:
      required: true
  - type: input
    id: mc
    attributes:
      label: "Your Minecraft version"
      description: "Write down your Minecraft version"
      placeholder: "Example: 1.16.5"
    validations:
        required: true
