name: publish

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: github-actions
    strategy:
        max-parallel: 1
    steps:
       - name: Download the pack files
         uses: robinraju/release-downloader@v1.9
         id: download-files
         with:
           fileName: "*.zip"
           latest: true
           preRelease: true
           tarBall: false
           zipBall: false

       - name: Publish to Modrinth and CurseForge
         uses: Kir-Antipov/mc-publish@v3.3
         with:
           name: "[${{ steps.download-files.outputs.tag_name }}] Viabackwards Plus"
           files: '*.zip'
           loaders: minecraft
           game-versions: "[1.16.2,1.20.4]"

           modrinth-id: v7n1ZsFg
           modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

           curseforge-id: 821967
           curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
           
           dependencies: |
             chime(required){modrinth:ubxU84eR}{curseforge:432776}#(ignore:github)
             cit-resewn(optional){modrinth:otVJckYQ}{curseforge:521427}#(ignore:github)
             respackopts(optional){modrinth:TiF5QWZY}#(ignore:curseforge,github)
             new-title(embedded){modrinth:oWMz79A6}#(ignore:curseforge,github)
