name: publish

on:
  release:
    types: [released,prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: github-actions
    strategy:
        max-parallel: 1
    steps:
       - name: Download the pack files
         uses: robinraju/release-downloader@v1
         id: download-files
         with:
           fileName: "*.zip"
           tag: ${{ github.event.release.tag_name }}
           latest: true
           tarBall: false
           zipBall: false

       - name: Publish to Modrinth and CurseForge
         uses: Kir-Antipov/mc-publish@v3.3
         with:
           name: ${{ steps.download-files.outputs.release_name }}
           files: '*.zip'
           loaders: minecraft
           game-versions: "[1.21.5,1.21.6]"

           modrinth-id: v7n1ZsFg
           modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

           curseforge-id: 821967
           curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

